// This is your Vercel-style serverless function,
// written in modern ES Module (ESM) syntax to match your project.

export default async (request, response) => {
  // We are expecting a POST request with JSON body
  if (request.method !== "POST") {
    // If not, send a 405 Method Not Allowed error
    response.status(405).json({ error: "Method Not Allowed" });
    return;
  }

  try {
    // Parse the incoming JSON body from the React app
    const { userPrompt, systemPrompt } = request.body;
    //await request.json();

    // Read the secret API key from environment variables
    // IMPORTANT: Server-side keys MUST NOT have the VITE_ prefix.
    // This key must be in your .env file as GEMINI_API_KEY=...
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      // This error will show in your 'vercel dev' terminal
      console.error(
        "API key (GEMINI_API_KEY) is not configured on the server."
      );
      // Send a generic error to the client
      response
        .status(500)
        .json({ error: "API key is not configured on the server." });
      return;
    }

    if (!userPrompt) {
      response
        .status(400)
        .json({ error: "userPrompt is missing from the request body" });
      return;
    }

    // --- Call the Google Gemini API ---

    // This is the URL for the model
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;

    // Construct the payload
    const payload = {
      contents: [{ parts: [{ text: userPrompt }] }],
    };

    // Add system instructions if they were provided
    if (systemPrompt) {
      payload.systemInstruction = {
        parts: [{ text: systemPrompt }],
      };
    }

    // Make the fetch request to the Google API
    const apiResponse = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!apiResponse.ok) {
      // If the Google API call failed, log the error and send it to the client
      const errorBody = await apiResponse.text();
      console.error("Google API Error:", errorBody);
      response
        .status(apiResponse.status)
        .json({ error: "Failed to fetch from Google API", details: errorBody });
      return;
    }

    // Parse the successful response from Google
    const data = await apiResponse.json();

    // --- Send the Successful Response to the React App ---

    // Extract the generated text
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      // This happens if the model sends an empty or blocked response
      console.error("No text generated, full response:", data);
      response
        .status(500)
        .json({ error: "No text was generated by the model.", details: data });
      return;
    }

    // Send the generated text back to the React app as a JSON object
    response.status(200).json({ text: generatedText });
  } catch (error) {
    // Handle any other unexpected errors (e.g., JSON parsing failed)
    console.error("An unexpected error occurred in /api/explain:", error);
    response.status(500).json({
      error: "An internal server error occurred.",
      details: error.message,
    });
  }
};
